; ESP-WROOM-32 carnivorous plant terrarium controller
; Framework: ESP-IDF only (Arduino framework and Arduino libraries are not used)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.flash_size = 2MB
board_upload.flash_size = 2MB
build_unflags = -fuse-cxa-atexit
